version: "3" 
services:
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - data-volume:/var/lib/postgresql
  redis:
    container_name: redis
    image: redis:6-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - data-volume:/data
volumes:
  data-volume: